@startuml burito search app
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

rectangle お店 #LightBlue {
  entity "shops" as shops {
    + shop_id : serial
    --
    * shop_name : varchar(100)
        '(Point, 4326)は緯度経度を２次元のデータで格納するという意味
    * location : GEOMETRY(Point, 4326)
  }
}

rectangle 住所 #lightgreen {
  entity "address" as address {
    + shop_id<<FK>>
    --
    * postcode : int
    * prefecture : varchar(100)
    * city : varchar(100)
    * street : varchar(100)
  }


}

rectangle 評価 #LightCoral{
  entity "evaluation" as evaluation {
    + evaluation_id : serial
    + shop_id : <<FK>>
    --
    * evaluation_number : int
    * comment : varchar(1000)
  }
}



shops ||--|| address
shops ||--o{ evaluation

@enduml