openapi: 3.0.0
info:
  title: ブリトー屋さんの場所管理 API
  version: 1.0.0
  description: 登録されてる店舗情報の取得、登録、更新、削除をする。
paths:
  /shops/info:
    get:
      summary: 全ての店舗情報を取得
      description: 登録されてるブリトー屋さんの店舗情報を取得する。
      responses:
        "200":
          description: 店舗情報取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  shopList:
                    type: array
                    items:
                      type: object
                      properties:
                        shop:
                          type: object
                          properties:
                            shop_id:
                              type: integer
                              example: 62
                            shop_name:
                              type: string
                              example: El Zocalo Burrito
                        address:
                          type: object
                          properties:
                            prefecture:
                              type: string
                              example: 大阪府
                            city:
                              type: string
                              example: 大阪市西区
                            street:
                              type: string
                              example: 北堀江１丁目９−６ ウイングス・ギザ
                            longitude:
                              type: number
                              format: float
                              example: 34.6742302
                            latitude:
                              type: number
                              format: float
                              example: 135.4958414
                        menuList:
                          type: object
                          properties:
                            items:
                              type: array
                              items:
                                type: string
                              example: ["tacos", "burrito", "guacamole"]
        "400":
          description: パラメータ不正
          content:
            application/json:
              example:
                code: 400
                message: Bad Request
        "404":
          description: お店が見つからない
          content:
            application/json:
              example:
                code: 404
                message: Not Found
        "408":
          description: タイムアウト
          content:
            application/json:
              example:
                code: 408
                message: Request Timeout
        "500":
          description: サーバーエラー
          content:
            application/json:
              example:
                code: 500
                message: Internal Server Error
    post:
      summary: 新しい店の情報を追加
      description: ブリトー屋さんの情報を新規登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shop_id:
                  type: integer
                  example: 1
                shop_name:
                  type: string
                  example: Elsocalo Burito
                longitude:
                  type: number
                  format: float
                  example: 139.6917
                latitude:
                  type: number
                  format: float
                  example: 35.6895
                prefecture:
                  type: string
                  example: 大阪府
                city:
                  type: string
                  example: 大阪市北区
                street:
                  type: string
                  example: 豊崎３丁目１９−３
                menu_list:
                  type: string
                  example: nachos,tacos,guacamole
      responses:
        "200":
          description: 登録成功
          content:
            application/json:
              example:
                code: 200
                message: "Success"
        "400":
          description: パラメータ不正
          content:
            application/json:
              example:
                code: 400
                message: Bad Request
        "404":
          description: お店が見つからない
          content:
            application/json:
              example:
                code: 400
                message: Bad Request
        "408":
          description: タイムアウト
          content:
            application/json:
              example:
                code: 408
                message: Request Timeout
        "500":
          description: サーバーエラー
          content:
            application/json:
              example:
                code: 500
                message: Internal Server Error
  /shops/info/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      summary: idで指定した店の情報を更新
      description: 該当の店の情報を更新する。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shop_id:
                  type: integer
                  example: 1
                shop_name:
                  type: string
                  example: Elsocalo Burito
                longitude:
                  type: number
                  format: float
                  example: 139.6917
                latitude:
                  type: number
                  format: float
                  example: 35.6895
                prefecture:
                  type: string
                  example: 大阪府
                city:
                  type: string
                  example: 大阪市北区
                street:
                  type: string
                  example: 豊崎３丁目１９−３
                menu_list:
                  type: string
                  example: nachos,tacos,guacamole
      responses:
        "200":
          description: 更新成功
          content:
            application/json:
              example:
                code: 200
                message: "Success"
        "400":
          description: パラメータ不正
          content:
            application/json:
              example:
                code: 400
                message: Bad Request
        "404":
          description: お店が見つからない
          content:
            application/json:
              example:
                code: 404
                message: Not Found
        "408":
          description: タイムアウト
          content:
            application/json:
              example:
                code: 408
                message: Request Timeout
        "500":
          description: サーバーエラー
          content:
            application/json:
              example:
                code: 500
                message: Internal Server Error

    delete:
      summary: idで指定した店の情報を削除
      description: 該当の店の情報を削除する。
      responses:
        "200":
          description: 削除成功
          content:
            application/json:
              example:
                code: 200
                message: Success
        "400":
          description: パラメータ不正
          content:
            application/json:
              example:
                code: 400
                message: Bad Request
        "404":
          description: お店が見つからない
          content:
            application/json:
              example:
                code: 404
                message: Not Found
        "408":
          description: タイムアウト
          content:
            application/json:
              example:
                code: 408
                message: Request Timeout
        "500":
          description: サーバーエラー
          content:
            application/json:
              example:
                code: 500
                message: Internal Server Error
